networks:
  bot:
    driver: bridge

services:
  web:
    build: .
    restart: always
    networks:
      - bot

  postgres:
    image: postgres:13
    container_name: pg_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
    postgres_data: